<?php  //[STAMP] 5c7f4f83ab30f552a4af0cf473f112e9
namespace Ffcms\Core\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Ffcms\Core\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
